# Generated by Django 4.0 on 2021-12-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='villagers',
            new_name='villager',
        ),
    ]
