# Generated by Django 4.0 on 2021-12-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_villagers_villager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='villager',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='villager',
            name='fav_color',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='villager',
            name='fav_song',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='villager',
            name='hobby',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='villager',
            name='is_sanrio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villager',
            name='subtype',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='villager',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
