# Generated by Django 4.0 on 2022-01-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_amiibo_coffee_furniture_game_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='amiibo',
            name='acquired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amiibo',
            name='villager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.villager'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='house_id',
            field=models.ManyToManyField(to='app.House'),
        ),
        migrations.AddField(
            model_name='game',
            name='villagers',
            field=models.ManyToManyField(to='app.Villager'),
        ),
        migrations.AddField(
            model_name='house',
            name='game',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='villager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.villager'),
        ),
        migrations.AddField(
            model_name='villager',
            name='coffee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coffee'),
        ),
        migrations.AddField(
            model_name='villager',
            name='personality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.personality'),
            preserve_default=False,
        ),
    ]
